app_home:
    path:         /{page}
    defaults:     { _controller: AppBundle:Home:index, page: 1 }
    requirements: { page: "\\d+" }

app_product:
    path:         /product/{id}
    defaults:     { _controller: AppBundle:Product:show }

app_register:
    path:         /register
    defaults:     { _controller: AppBundle:Register:index }

app_login:
    path:         /login
    defaults:     { _controller: AppBundle:Security:login }

app_logout:
    path:         /logout
    defaults:     { _controller: AppBundle:Security:logout }